# Generated by Django 6.0 on 2025-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Category_Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
    ]
