# Generated by Django 5.2.6 on 2025-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydata',
            name='Category_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Category Images'),
        ),
    ]
