# Generated by Django 5.2.6 on 2025-12-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_categorydata_category_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryData',
            new_name='CategoryDB',
        ),
    ]
