# Generated by Django 5.2.6 on 2025-12-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_categorydata_categorydb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDB',
            new_name='CategoryData',
        ),
    ]
