# Generated by Django 5.2.6 on 2025-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_rename_categorydb_categorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=30, null=True)),
                ('CategoryDescription', models.CharField(blank=True, max_length=30, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='category images')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryData',
        ),
    ]
