# Generated by Django 5.2.6 on 2025-12-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_categorydb_delete_categorydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Category_Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='category_image')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoryDB',
        ),
    ]
