# Generated by Django 5.2.6 on 2025-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_categorydata_delete_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Brand', models.CharField(blank=True, max_length=30, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Short_Description', models.TextField(blank=True, null=True)),
                ('Detailed_Description', models.TextField(blank=True, null=True)),
                ('Product_Image1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_Image2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Product_Image3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
