# Generated by Django 5.2.6 on 2025-12-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='UserName',
            new_name='Username',
        ),
    ]
