# Generated by Django 5.2.6 on 2025-12-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_rename_username_userregistration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
