# Generated by Django 5.2.6 on 2025-12-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_contactusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusdata',
            name='Subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
