# Generated by Django 5.2.6 on 2026-02-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_contactusdata_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
