# Generated by Django 5.2.6 on 2026-02-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
