# Generated by Django 5.2.6 on 2026-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_cartdata_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=30, null=True)),
                ('Mobile', models.IntegerField()),
                ('Place', models.CharField(blank=True, max_length=30, null=True)),
                ('Post_Code', models.IntegerField()),
                ('Username', models.CharField(max_length=30, null=True)),
                ('Total_Price', models.CharField(blank=True, max_length=30, null=True)),
                ('Message', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
