# Generated by Django 5.2.6 on 2026-02-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_billingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdata',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
